# -*- mode: python ; coding: utf-8 -*-

block_cipher = None


a = Analysis(
    ['launcher.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('templates', 'templates'),
        ('static', 'static'),
        ('borderou', 'borderou'),
        ('CardCec', 'CardCec'),
        ('classes', 'classes'),
    ],
    hiddenimports=[
        'pandas',
        'openpyxl',
        'openpyxl.cell._writer',
        'openpyxl.styles',
        'werkzeug.serving',
        'pystray',
        'PIL',
        'PIL._tkinter_finder',
        'requests',
        'packaging',
        'borderou.main',
        'borderou.borderou_to_import_transformer',
        'borderou.csv_cleaner',
        'borderou.csv_to_xlsx_converter',
        'borderou.to_csv',
        'CardCec.pos_processor',
        'CardCec.xlsx_to_csv',
        'CardCec.view_output',
        'classes.valoare_sgr',
        'classes.valoare_minus',
        'classes.format_add_column',
        'classes.excel_data_extractor',
        'classes.excel_processor',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['torch', 'torchvision', 'torchaudio', 'tensorflow', 'matplotlib', 'scipy', 'pytest', 'unittest'],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='ExcelProcessor',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    icon='excel-processor-icon.ico',
)
